### ISSUE TITLE
Newly installed app has over 100 content-groups

### ISSUE THREAD

**Issue by iJungleboy** [2sic/app-accordion-bootstrap3#1]
...this are hidden items in the scope "2SexyContent-System" which have no use. Please delete for next release.

**Comment by iJungleboy** [comment]
@ropalko is this still an open issue or has this been fixed a long time ago?

**Comment by iJungleboy** [comment]
@ropalko pls close this after clean-up.

**Comment by ropalko** [comment]
Updated in Version 3.0.2
