### ISSUE TITLE
accordion app bug: navigates to home page with strange url when editing or opening

### ISSUE THREAD

**Issue by patrickjlee** [2sic/app-accordion-bootstrap3#25]
I'm running a local Oqtane site in debug (localhost:44357/). 

When editing (or sometimes even just clicking on a 2nd accordion app on a new test page), it seems to treat it as a hyperlink with names like localhost:44357/#a-2985 which takes me away from the page with the accordion on and to the site's home page.

**Comment by iJungleboy** [comment]
This appears to be related to an issue with the Razor navigation system; it "intercepts" certain actions.

Could you specify Oqtane version and rendering / interactivity modes?

**Comment by patrickjlee** [comment]
Thanks - I believe I have the latest version of Oqtane (6.0.0) , with render set to Interactive (because I am using the StudioElf.Theme.JetPack.Theme, StudioElf.Theme.JetPack.Client.Oqtane theme).  But I didn't reinstall the accordion app, instead I just replaced the two files (script.min.js and script.min.js.map) as per https://github.com/2sic/app-accordion/issues/24#issuecomment-2530986411.

**Comment by iJungleboy** [comment]
@ropalko maybe we should just change the accordion to _not_ change the URL on Oqtane (I think something like `$2sxc.env.platform()` https://docs.2sxc.org/api/js/SxcGlobalEnvironment.html#Api_Js_SxcJs_SxcGlobalEnvironment.

This would reduce it's functionality, but at least not break links for now.

What do you think @ropalko ?

**Comment by ropalko** [comment]
I think its a good idea, i will change this.

**Comment by ropalko** [comment]
Hello @patrickjlee 
I have updated the code. Please apply the following changes:

These are located under /bs5/dist
[scripts.min.js](https://github.com/2sic/app-accordion/blob/master/bs5/dist/scripts.min.js)
[scripts.min.js.map](https://github.com/2sic/app-accordion/blob/master/bs5/dist/scripts.min.js.map)

This ist located under /bs5
[Assets.cshtml](https://github.com/2sic/app-accordion/blob/master/bs5/Assets.cshtml)
In this file you can also simply add the line: @Kit.Page.Activate("2sxc.JsCore")

**Comment by patrickjlee** [comment]
Many thanks @ropalko! That does seem to have fixed the issue :)
